Add test for duplicate keys
theupdateframework/tuf-conformance pull request #108
Opened 2024-08-05 12:37 UTC by AdamKorcz

Add test that is specified in https://github.com/theupdateframework/tuf-conformance/pull/86#issuecomment-2259995260 without the bonus test.

2024-08-05 13:55 UTC, jku reviewed
The code comments are nits, the return value might be useful to check mostly as documentation to test reader: otherwise it's hard to figure out what is actually expected

> The two clients seem to disagree on whether root metadata should update if there are duplicate keys. As such, python-tuf does not fail on meeting the threshold, but rather because the root has duplicate keys. 

Can you be more specific, I can't find code that would fail on duplicates in  `root.roles["role"].keyids`? Do you mean signatures?

2024-08-05 13:55 UTC, jku commented on tuf_conformance/test_keys.py
> +    client.refresh(init_data)
asserts for success/failure on the refresh calls would make it more readable

2024-08-05 13:55 UTC, jku commented on tuf_conformance/test_keys.py
> +    repo.bump_root_by_one()  # v2
nit: this call seems irrelevant to the test, or am I missing something?

2024-08-05 14:02 UTC, jku approved these changes

2024-08-05 14:07 UTC, jku commented
> Can you be more specific, I can't find code that would fail on duplicates in `root.roles["role"].keyids`? Do you mean signatures?

oh I see now, you mean the test failing in CI. I'll have a look

2024-08-05 15:11 UTC, AdamKorcz commented
> > Can you be more specific, I can't find code that would fail on duplicates in `root.roles["role"].keyids`? Do you mean signatures?
> 
> oh I see now, you mean the test failing in CI. I'll have a look
> 
> EDIT:
> 
> ```
>         if len(set(keyids)) != len(keyids):
>             raise ValueError(f"Nonunique keyids: {keyids}")
> ```
> 
> python tuf indeed will not deserialize metadata with duplicate keyids... we'll have to decide how we continue. This still seems like an acceptable choice by python-tuf: I wouldn't want to force them to change for the test...

Yes, for the record, the test is currently set up so that python-tuf fails, but that does not mean that it - or go-tuf for that matter - is wrong. The interesting part here is that the two clients behave differently.

2024-08-14 13:26 UTC, jku commented
a way to move forward here would be to accept either case for now:
* failure to refresh metadata with duplicate keyids -> **Test succeeds**
* metadata with duplicate keyids works but keyid is not double counted for threshold -> **Test succeeds**
* metadata with duplicate keyids works and keyid is double counted for threshold -> **Test Fails**

2024-08-15 07:38 UTC, jku commented
I think we can close this one: 
* test_duplicate_keys_root is very close to testing the _"fake reaching threshold with duplicate keyids"_ case
* #147 has been filed to make that test even more effective
* #143 has been filed for the inconsistent behaviour between clients WRT duplicate keyids

2024-08-15 09:25 UTC, jku requested changes
marking "request changes" to remove my accidental approval: I think we might just be able to close this without merging

2024-09-27 07:48 UTC, jku commented
Closing, everything is handled by other issues

2024-09-27 07:48 UTC, closed without merging